# Generated by Django 4.2.1 on 2023-07-02 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notatki', '0003_rename_user_userprofile_user_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='notes',
            field=models.ManyToManyField(blank=True, to='notatki.note'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
